name: Wikicau
author: Admin Wikicau
description: Tips dan trik memelihara burung kicau
avatar: /images/wikicau.webp
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram:
  linkedin: 
  pinterest:
  rss: rss
  twitter: androbuntuco
  youtube: channel/UCNDPQGDYpgaglAp7eFBo_sQ
disqus: wikicau
google_analytics: UA-125094882-2
url: http://www.wikicau.com/
enforce_ssl: https://www.wikicau.com/
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :compressed # You might prefer to minify using :compressed
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
include: ['_pages']
paginate: 10
paginate_path: /page:num/
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME